"""The editor's Python completion surface: generated by the sidecar, served by the API.

Run: uv run python tests/pyapi_smoke.py

Checks the three things it is built from — corr_vars helper modules parsed as source, the
names a snippet gets for free (import header + `var` + `cohort`), and the installed polars —
and then that `GET /sources/{key}/pyapi` serves the file, refuses the wrong source, and 404s
where no sidecar ever wrote one.
"""
import os
import sys
import tempfile
from pathlib import Path

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "sync"))

import pyapi  # noqa: E402  — the sidecar's generator

HELPERS_PY = '''
"""Helpers shared by cub_hdp variable functions."""
import polars as pl


def get_cub_hdp_config(cohort, *, strict: bool = True) -> CubHdpSourceDict:
    """Return the cub_hdp source configuration.

    A second line the completion popup has no room for.
    """
    return cohort.sources["cub_hdp"]


def _private(x):
    """Not part of the surface."""
'''

UTILS_INIT_PY = "from .time import *  # noqa: F401 F403\n"
UTILS_TIME_PY = '''
def merge_consecutive(df, gap: int = 0):
    """Merge rows whose intervals touch."""
'''

VARIABLES_PY = '''
from __future__ import annotations

from functools import partial

import polars as pl
from corr_vars import logger, __
import corr_vars.sources.cub_hdp.helpers as helpers

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from corr_vars.core import Cohort
'''

TYPING_PY = '''
from dataclasses import dataclass, field


@dataclass
class VariableContext:
    """Slim context passed to VariableCallable py functions.

    Args:
        var_name (str): The variable name.
        dynamic (bool): Whether the variable is dynamic (time-series).
        files (Mapping[str, Path]): Data files attached to the variable definition,
            keyed by their path relative to the variable's file directory.
    """

    var_name: str
    dynamic: bool
    files: Mapping[str, Path] = field(default_factory=dict)
'''

COHORT_PY = '''
class Cohort:
    """A cohort of observations."""

    def add_variable(self, var_name: str, overwrite: bool = False) -> None:
        """Add a variable to the cohort."""

    @property
    def obs(self) -> pl.DataFrame:
        """The observation frame."""

    def _internal(self) -> None:
        """Hidden."""
'''

doc = pyapi.build(
    source_key="cub_hdp",
    variables_py=VARIABLES_PY,
    helpers={"helpers": HELPERS_PY, "utils": UTILS_INIT_PY, "utils.time": UTILS_TIME_PY},
    typing_py=TYPING_PY,
    cohort_py=COHORT_PY,
)

# (a) helper modules: name, full signature with defaults, return annotation, summary line only.
fn = doc["modules"]["helpers"]["functions"]
assert [f["name"] for f in fn] == ["get_cub_hdp_config"], fn  # `_private` stays private
assert fn[0]["signature"] == "(cohort, *, strict: bool=True)", fn[0]
assert fn[0]["returns"] == "CubHdpSourceDict", fn[0]
assert fn[0]["doc"] == "Return the cub_hdp source configuration.", fn[0]
# A package's star re-exports are folded into the alias a snippet actually writes.
assert [f["name"] for f in doc["modules"]["utils"]["functions"]] == ["merge_consecutive"], doc["modules"]["utils"]

# (b) the snippet's scope: the runtime import header (never the TYPE_CHECKING block, and never
# the __future__ directive), plus var/cohort.
names = {g["name"] for g in doc["globals"]}
assert {"partial", "pl", "logger", "__", "helpers", "TYPE_CHECKING"} <= names, sorted(names)
assert "Cohort" not in names and "annotations" not in names, sorted(names)

var = {m["name"]: m for m in doc["context"]["var"]["members"]}
assert set(var) == {"var_name", "dynamic", "files"}, sorted(var)
assert var["files"]["returns"] == "Mapping[str, Path]", var["files"]
assert var["files"]["doc"].startswith("Data files attached to the variable definition"), var["files"]

cohort = {m["name"]: m for m in doc["context"]["cohort"]["members"]}
assert set(cohort) == {"add_variable", "obs"}, sorted(cohort)  # `_internal` is not surface
assert cohort["add_variable"]["signature"] == "(var_name: str, overwrite: bool=False)", cohort
assert cohort["obs"]["kind"] == "attribute" and cohort["obs"]["returns"] == "pl.DataFrame", cohort

# (c) the installed package, introspected — members that raise on lookup are skipped, not fatal.
pl_module = doc["modules"]["pl"]
assert pl_module["origin"] == "package" and pl_module["module"] == "polars"
assert any(f["name"] == "read_csv" for f in pl_module["functions"]), len(pl_module["functions"])
frame = pl_module["types"]["DataFrame"]["members"]
assert any(m["name"] == "group_by" and m["signature"] for m in frame), len(frame)

# --- the endpoint -----------------------------------------------------------------------
staging = tempfile.mkdtemp()
pyapi_path = os.path.join(staging, pyapi.PYAPI_NAME)
pyapi.write(Path(staging), doc)

db_path = os.path.join(tempfile.mkdtemp(), "pyapi.db")
os.environ["DATABASE_URL"] = f"sqlite:///{db_path}"
os.environ["JWT_SECRET"] = "test-secret-that-is-at-least-32-bytes-long!!"
os.environ["APP_SHARED_SECRET"] = ""
os.environ["BOOTSTRAP_ADMIN_USERNAME"] = "admin"
os.environ["BOOTSTRAP_ADMIN_PASSWORD"] = "admin"
os.environ.setdefault("SCHEMA_DIR", "reference/schema")
os.environ["IMPORT_REFERENCE_ON_FIRST_RUN"] = "false"
os.environ["REFERENCE_PYAPI_FILE"] = pyapi_path

import warnings  # noqa: E402

warnings.filterwarnings("ignore")

from fastapi.testclient import TestClient  # noqa: E402

from api.main import app  # noqa: E402

with TestClient(app) as c:
    assert c.get("/sources/cub_hdp/pyapi").status_code in (401, 403)  # can_read, like its neighbours
    tok = c.post("/auth/login", json={"username": "admin", "password": "admin"}).json()
    c.headers["authorization"] = f"Bearer {tok['access_token']}"

    r = c.get("/sources/cub_hdp/pyapi")
    assert r.status_code == 200, r.text
    assert r.json()["modules"]["helpers"]["functions"][0]["name"] == "get_cub_hdp_config", r.text
    # One document describes one source's scope; another key gets nothing, not this one's.
    assert c.get("/sources/reprodicu/pyapi").status_code == 404

    # A deployment without the sidecar simply has no file.
    os.remove(pyapi_path)
    r = c.get("/sources/cub_hdp/pyapi")
    assert r.status_code == 404 and "vars-sync" in r.json()["detail"], r.text

print("PYAPI SMOKE OK")
