import json
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.orm import Session

from ..config import settings
from ..db import get_db
from ..deps import require_capability
from ..models import Source, Taxonomy
from ..schema_registry import registry
from ..schemas import SourceOut, SourceTypesOut, TaxonomyOut
from ..security import CAN_READ

# Reference metadata (sources, schemas, taxonomies) is authenticated read-only data, same as
# concept content — every route here requires can_read.
router = APIRouter(tags=["reference"], dependencies=[Depends(require_capability(CAN_READ))])


@router.get(
    "/sources",
    response_model=list[SourceOut],
    openapi_extra={"x-public": True},
    summary="List sources",
)
def list_sources(db: Session = Depends(get_db)):
    """The available sources a concept can be defined for, with the config types each one
    supports and whether its definitions are governed by a JSON schema."""
    # supported_types is derived live from the schema folder (the source of truth), so it
    # never drifts from what's actually on disk. The DB column is a boot-time snapshot.
    return [
        {
            "key": s.key,
            "nicename": s.nicename,
            "supported_types": registry.supported_types(s.key),
            "schema_governed": registry.is_schema_governed(s.key),
        }
        for s in db.scalars(select(Source).order_by(Source.key))
    ]


@router.get(
    "/sources/{key}/types",
    response_model=SourceTypesOut,
    openapi_extra={"x-public": True},
    summary="List a source's config types",
)
def source_types(key: str, db: Session = Depends(get_db)):
    """The config types supported by one source."""
    if registry.get_umbrella_schema(key) is None and not registry.supported_types(key):
        if db.scalar(select(Source).where(Source.key == key)) is None:
            raise HTTPException(404, f"Source '{key}' not found")
    return {
        "source": key,
        "supported_types": registry.supported_types(key),
        "schema_governed": registry.is_schema_governed(key),
    }


@router.get(
    "/sources/{key}/schema",
    openapi_extra={"x-public": True},
    summary="Get a source's umbrella JSON schema",
)
def source_umbrella_schema(key: str):
    """The umbrella JSON schema for a source (the discriminated union over its types)."""
    schema = registry.get_umbrella_schema(key)
    if schema is None:
        raise HTTPException(404, f"No umbrella schema for source '{key}'")
    return schema


@router.get(
    "/sources/{key}/schema/{type}",
    openapi_extra={"x-public": True},
    summary="Get the JSON schema for a source type",
)
def source_type_schema(key: str, type: str):
    """The JSON schema for one config type of a source."""
    schema = registry.get_type_schema(key, type)
    if schema is None:
        raise HTTPException(
            404,
            f"No schema for source '{key}' type '{type}'; "
            f"available: {registry.supported_types(key)}",
        )
    return schema


@router.get("/sources/{key}/pyapi", summary="Get a source's Python API surface")
def source_pyapi(key: str):
    """The names a `py` snippet for this source can call, for editor autocomplete: the
    corr_vars helpers, what the snippet's scope already holds (`pl`, `var`, `cohort`, …) and
    the members of polars/pandas — each with its signature and the first line of its
    docstring.

    Name + signature + docstring, **not** type inference: nothing here knows what a chained
    expression evaluates to, so `var.data.group_by(...).<tab>` is outside what this can
    answer. That needs a real language server (Pyright in WASM, as the editor's own comments
    anticipate) and is deliberately not built here.

    Generated by the vars-sync sidecar (see `sync/pyapi.py`, which documents the shape) and
    served from the reference dir. A deployment without the sidecar has no file, hence 404.
    """
    path = Path(settings.reference_pyapi_file)
    if not path.is_file():
        raise HTTPException(
            404,
            f"No Python API surface available; '{path.name}' is generated by the vars-sync "
            f"sidecar, which this deployment does not run.",
        )
    try:
        document = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise HTTPException(500, f"Could not read {path.name}: {exc}") from exc
    # One source's snippets, one document. Serving cub_hdp's surface for a source whose
    # snippets run in a different scope would be worse than admitting there is nothing.
    if document.get("source") != key:
        raise HTTPException(
            404, f"No Python API surface for source '{key}' (the file describes "
                 f"'{document.get('source')}')"
        )
    return document


@router.get("/schemas")
def all_type_schemas(db: Session = Depends(get_db)):
    """Every leaf type schema, keyed {source: {type: schema}}, for bulk form preload.

    Only schema-governed sources appear (others have nothing to render a form from).
    """
    out: dict[str, dict] = {}
    for s in db.scalars(select(Source).order_by(Source.key)):
        types = registry.supported_types(s.key)
        if not types:
            continue
        out[s.key] = {t: registry.get_type_schema(s.key, t) for t in types}
    return out


@router.get(
    "/taxonomies",
    response_model=list[TaxonomyOut],
    openapi_extra={"x-public": True},
    summary="List taxonomies",
)
def list_taxonomies(db: Session = Depends(get_db)):
    """The taxonomies concepts are named within. A taxonomy provides the namespace of
    concept `name`s (identifiers) used throughout the API."""
    return [
        {"key": t.key, "name": t.name, "version": t.version}
        for t in db.scalars(select(Taxonomy).order_by(Taxonomy.key))
    ]
