"""vars-sync — TEMPORARY bridge until the Concepts API can query variables itself.

Polls the upstream vars repo (``cub-corr/corr-vars``) via the GitHub API. When the branch
tip moves, it stages that commit's state into a directory shared with the API (a Docker
volume) and calls the API's token-guarded ``POST /internal/reimport``, which upserts the
reference configs from what it finds there: a new variable becomes a concept, one whose
definition moved gets a new version, and the rest are left exactly as they are. What is
staged:

* the configured ``FILES`` — ``vars.json`` + ``variables.py``, plus the
  ``drug_mapping.parquet`` / ``lab_mapping.parquet`` mappings behind the auto-generated
  medication/laboratory variables (the API regenerates those variables on each reimport).
  These are written **by basename**, collapsing nested source paths into the flat reference
  dir the API reads;
* ``files/<relpath>`` — every data file the source ships (a postcode table, a pickled
  classifier), under its path in the mapping tree. The API keeps these in the source's
  versioned file library and mints a version wherever the bytes moved;
* ``pyapi.json`` — the names, signatures and docstrings a ``py`` snippet can call, for the
  app's code editor (generated by ``sync/pyapi.py``; served by the API, not imported);
* ``<key>_vars.json`` / ``<key>_units.json`` for each source in ``EXTRA_SOURCES``.

After the reimport it also posts whatever this deployment *computes* rather than fetches —
see the ``row_source`` seam, a no-op in the public build — to the API's
``POST /internal/variables/upsert``. Those variables never touch the shared volume.

Everything but the last bullet belongs to the **primary** source (``MAPPING_DIR``), the one
whose variables carry Python snippets. ``EXTRA_SOURCES`` names sources that consist of
nothing but their definitions — reprodICU is one: no ``variables.py``, so no data files to
stage and no completion surface, and those passes are skipped rather than reported as missing.
Their files are prefixed with the source key because the flat reference dir has room for
exactly one ``vars.json``, and the prefix is the name the API's ``REFERENCE_DATASETS`` reads
them under.

Why polling and not a webhook: GitHub can only deliver events to a publicly reachable URL.
This service runs on a private network, so it polls instead — cheaply, because the commits
API returns just the tip SHA. Delete this whole directory (and the sidecar/endpoint) once
real API-based querying ships.

It can also export per-concept clinical documentation from a Notion database: every page
(titled with the concept's canonical name) is flattened to the fields in
``notion_fields.json`` (a user-editable column mapping) and written to
``notion_docs.json`` in the reference dir; the importer applies it to the concept rows on
the reimport this service triggers. Optional — configured entirely by the NOTION_* env vars.

Config via env:
  GITHUB_REPO        owner/name of the vars repo (e.g. cub-corr/corr-vars)   [required unless Notion-only]
  GITHUB_BRANCH      branch to track                                          [default: main]
  GITHUB_TOKEN       read token for the (private) repo                        [required for private]
  POLL_INTERVAL      seconds between tip checks                               [default: 60]
  MAPPING_DIR        repo dir holding variables.py and its data files         [default: src/corr_vars/sources/cub_hdp/mapping]
  SOURCE_KEY         source the pyapi is served under (API IMPORT_SOURCE_KEY)  [default: derived from MAPPING_DIR]
  FILES              comma-separated repo paths to sync (written by basename)  [default: MAPPING_DIR's vars.json, variables.py, drug/drug_mapping.parquet, lab/lab_mapping.parquet]
  EXTRA_SOURCES      definitions-only sources, `key=repo/dir` comma-separated  [optional]
  TARGET_DIR         where to write the files (shared with the API)          [default: /data/reference]
  API_INTERNAL_URL   base URL of the Concepts API                            [default: http://api:8000]
  INTERNAL_TOKEN     shared secret for POST /internal/reimport               [required]
  NOTION_API_KEY     integration token; unset = Notion export off            [optional]
  NOTION_DATABASE_ID the documentation database                              [required with key]
  NOTION_FIELDS_FILE column-mapping config                                    [default: notion_fields.json next to this script]
  NOTION_POLL_INTERVAL  seconds between full Notion refetches                [default: 600]
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import shutil
import sys
import time
from pathlib import Path, PurePosixPath

import httpx

import pyapi
import row_source

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s %(message)s"
)
log = logging.getLogger("vars-sync")

REPO = os.environ.get("GITHUB_REPO", "")
BRANCH = os.environ.get("GITHUB_BRANCH", "main")
TOKEN = os.environ.get("GITHUB_TOKEN", "")
INTERVAL = int(os.environ.get("POLL_INTERVAL", "60"))
# The upstream package directory holding variables.py and the data files it reads. Both the
# flat FILES fetch and the recursive subtree fetch hang off it, so they can't drift apart.
# `or` rather than a get() default throughout: compose passes an unset variable through as the
# empty string, which would otherwise read as "sync nothing".
MAPPING_DIR = (
    os.environ.get("MAPPING_DIR", "").strip() or "src/corr_vars/sources/cub_hdp/mapping"
).strip("/")
FILES = [
    f.strip()
    for f in (
        os.environ.get("FILES", "").strip()
        or f"{MAPPING_DIR}/vars.json,"
        f"{MAPPING_DIR}/variables.py,"
        f"{MAPPING_DIR}/drug/drug_mapping.parquet,"
        f"{MAPPING_DIR}/lab/lab_mapping.parquet"
    ).split(",")
    if f.strip()
]
TARGET_DIR = Path(os.environ.get("TARGET_DIR", "/data/reference"))
# Where the source's data files are staged, inside TARGET_DIR. The API reads the tree under the
# same name (see api/config.py reference_files_dir).
FILES_SUBDIR = "files"
# Suffixes that count as a data file. Mirrors the API's upload allowlist — a file staged here
# has to be something the API will accept into a source's library.
DATA_SUFFIXES = (".csv", ".parquet", ".pkl", ".json", ".xlsx", ".txt", ".tsv")
# The module the scan reads. Its own name matters: `Path(__file__).parent` is resolved by
# taking the parent of this path, which is how a reference is anchored to MAPPING_DIR.
VARIABLES_MODULE = "variables.py"
# What a definitions-only source consists of, staged as `<key>_vars.json` / `<key>_units.json`.
# Not configurable: these two names are the whole contract with the API's REFERENCE_DATASETS,
# and anything richer (a variables.py and the files it reads, the helpers behind pyapi.json)
# is by definition the primary source's.
EXTRA_SOURCE_FILES = ("vars.json", "units.json")

# --- what the editor's completion surface is built from (see sync/pyapi.py) ------------------
# All derived from MAPPING_DIR — .../sources/<source>/mapping — so pointing the sidecar at a
# different source moves them together. SOURCE_KEY must match the API's IMPORT_SOURCE_KEY:
# the API serves the generated file at GET /sources/<key>/pyapi.
_SOURCE_DIR = str(PurePosixPath(MAPPING_DIR).parent)
_PACKAGE_DIR = _SOURCE_DIR.split("/sources/")[0]
SOURCE_KEY = os.environ.get("SOURCE_KEY", "").strip() or PurePosixPath(_SOURCE_DIR).name
HELPERS_FILE = f"{_SOURCE_DIR}/helpers.py"
UTILS_DIR = f"{_PACKAGE_DIR}/utils"
# `VariableContext` (what a snippet gets as `var`) and `Cohort` (as `cohort`).
TYPING_FILE = f"{_PACKAGE_DIR}/definitions/typing.py"
COHORT_FILE = f"{_PACKAGE_DIR}/core/cohort.py"


def _parse_extra_sources(raw: str) -> list[tuple[str, str]]:
    """``key=repo/dir`` pairs -> ``[(source key, mapping dir), …]``.

    A malformed entry is dropped with a warning rather than taken as the empty repo root,
    which would try to stage the top of the repo as somebody's definitions.
    """
    out: list[tuple[str, str]] = []
    for item in raw.split(","):
        key, _, path = item.strip().partition("=")
        key, path = key.strip(), path.strip().strip("/")
        if not item.strip():
            continue
        if not key or not path:
            log.warning("ignoring EXTRA_SOURCES entry %r; expected `key=repo/dir`", item.strip())
            continue
        out.append((key, path))
    return out


EXTRA_SOURCES = _parse_extra_sources(os.environ.get("EXTRA_SOURCES", ""))
API_URL = os.environ.get("API_INTERNAL_URL", "http://api:8000").rstrip("/")
INTERNAL_TOKEN = os.environ.get("INTERNAL_TOKEN", "")

NOTION_API_KEY = os.environ.get("NOTION_API_KEY", "")
NOTION_DATABASE_ID = os.environ.get("NOTION_DATABASE_ID", "")
NOTION_FIELDS_FILE = Path(
    os.environ.get("NOTION_FIELDS_FILE", str(Path(__file__).parent / "notion_fields.json"))
)
NOTION_INTERVAL = int(os.environ.get("NOTION_POLL_INTERVAL", "600"))

GITHUB = "https://api.github.com"
NOTION = "https://api.notion.com/v1"
NOTION_VERSION = "2025-09-03"


def _gh_headers(raw: bool = False) -> dict[str, str]:
    headers = {
        "Accept": "application/vnd.github.raw+json" if raw else "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"
    return headers


def latest_sha(client: httpx.Client) -> str:
    r = client.get(f"{GITHUB}/repos/{REPO}/commits/{BRANCH}", headers=_gh_headers())
    r.raise_for_status()
    return r.json()["sha"]


def fetch_file(client: httpx.Client, path: str, ref: str) -> bytes:
    # `raw` Accept returns the file bytes directly (works for blobs up to 1 MB).
    r = client.get(
        f"{GITHUB}/repos/{REPO}/contents/{path}",
        params={"ref": ref},
        headers=_gh_headers(raw=True),
    )
    r.raise_for_status()
    return r.content


def list_tree(client: httpx.Client, ref: str) -> dict[str, str]:
    """``{repo path: blob sha}`` for the whole repo at `ref`.

    One recursive trees call rather than a walk of the contents API: the listing is then a
    single request and a consistent snapshot of one commit, and both the data-file scan and
    the pyapi generation can filter the same result instead of asking twice.
    """
    r = client.get(
        f"{GITHUB}/repos/{REPO}/git/trees/{ref}",
        params={"recursive": "1"},
        headers=_gh_headers(),
    )
    r.raise_for_status()
    data = r.json()
    if data.get("truncated"):
        # >100k entries. Not a repo we can sync file-by-file; say so rather than silently
        # syncing whatever half of the tree came back.
        log.warning("git tree for %s@%s was truncated; the file scan may be incomplete", REPO, ref[:8])
    return {
        entry["path"]: entry["sha"]
        for entry in data.get("tree", [])
        if entry.get("type") == "blob"
    }


def _under(tree: dict[str, str], prefix: str) -> dict[str, str]:
    """The subtree below `prefix`, re-keyed relative to it."""
    at = f"{prefix}/"
    return {path[len(at):]: sha for path, sha in tree.items() if path.startswith(at)}


def fetch_blob(client: httpx.Client, sha: str) -> bytes:
    """Raw bytes of one git blob. Unlike the contents API (which caps at 1 MB) this serves
    blobs up to 100 MB, which is what the pickled models need."""
    r = client.get(
        f"{GITHUB}/repos/{REPO}/git/blobs/{sha}",
        headers={**_gh_headers(), "Accept": "application/vnd.github.raw"},
    )
    r.raise_for_status()
    return r.content


# --- the source's data files ----------------------------------------------------------------


def _looks_like_data_file(name: str) -> bool:
    """True for something shaped like a data file name. The stem check keeps a bare suffix
    literal (``".parquet"`` used in a `str.replace`) from being mistaken for a filename."""
    p = PurePosixPath(name)
    return bool(p.stem) and p.suffix.lower() in DATA_SUFFIXES


def sync_variable_files(
    client: httpx.Client, sha: str, tree: dict[str, str]
) -> list[str]:
    """Stage every data file in the source's mapping tree under ``files/<relpath>``.

    The tree **is** the library. There used to be a manifest here — an AST walk over
    ``variables.py`` working out which variable read which file, so the API could attach each
    file to the right config — and it is gone with the model it served. A snippet now names its
    files by uuid (``getfile("<uuid>")``), a uuid the API mints, so nothing outside the API can
    say which variable needs what, and nothing needs to: the API versions every file it is given
    and each definition says for itself which of them it reads.

    That makes the rule here simply "every data file this source ships". Excluded are the ones
    already staged flat by ``FILES`` (``vars.json``, the drug/lab mapping parquets): those are
    inputs to the import itself, not files a snippet reads, and staging them twice would put
    multi-megabyte duplicates in the library.

    The directory is rebuilt from scratch each time, so a file upstream deleted stops being
    staged. It is **not** retired in the API by that: a staging run that half-failed would
    otherwise retire a source's whole library, and retiring is a decision made in the app.
    """
    mapping = _under(tree, MAPPING_DIR)
    staged_flat = {PurePosixPath(f).name for f in FILES}
    needed = sorted(
        rel
        for rel in mapping
        if _looks_like_data_file(rel) and PurePosixPath(rel).name not in staged_flat
    )

    files_root = TARGET_DIR / FILES_SUBDIR
    shutil.rmtree(files_root, ignore_errors=True)
    for rel in needed:
        target = files_root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(fetch_blob(client, mapping[rel]))
    log.info(
        "staged %d data file(s) @ %s: %s", len(needed), sha[:8], ", ".join(needed) or "(none)"
    )
    return needed


def sync_pyapi(client: httpx.Client, sha: str, tree: dict[str, str]) -> None:
    """Regenerate ``pyapi.json`` — the completion surface for the app's code editor.

    Read the shape it produces in ``sync/pyapi.py``; the API serves it at
    ``GET /sources/{key}/pyapi``. Failure here is logged, never fatal: a missing completion
    list degrades the editor, while a sidecar that stopped syncing definitions over it would
    be a far worse trade.
    """
    variables_py = TARGET_DIR / VARIABLES_MODULE
    if not variables_py.is_file():
        log.warning("%s was not synced; skipping the pyapi generation", VARIABLES_MODULE)
        return

    # helpers.py of this source, plus every module of the corr_vars utils package — the two
    # places variables.py imports its shared helpers from.
    wanted = {
        p: s
        for p, s in tree.items()
        if p == HELPERS_FILE or (p.startswith(f"{UTILS_DIR}/") and p.endswith(".py"))
    }
    helpers = {
        pyapi.alias_for(path, UTILS_DIR): fetch_blob(client, sha_).decode("utf-8", "replace")
        for path, sha_ in sorted(wanted.items())
    }
    if not helpers:
        log.warning("no helper modules found under %s / %s", HELPERS_FILE, UTILS_DIR)

    def _read(path: str) -> str | None:
        blob = tree.get(path)
        if blob is None:
            log.warning("%s not found at %s; part of the pyapi will be missing", path, sha[:8])
            return None
        return fetch_blob(client, blob).decode("utf-8", "replace")

    document = pyapi.build(
        source_key=SOURCE_KEY,
        variables_py=variables_py.read_text(),
        helpers=helpers,
        typing_py=_read(TYPING_FILE),
        cohort_py=_read(COHORT_FILE),
    )
    pyapi.write(TARGET_DIR, document)


def sync_extra_sources(client: httpx.Client, sha: str, tree: dict[str, str]) -> None:
    """Stage the definitions of every source in EXTRA_SOURCES as ``<key>_<basename>``.

    Driven off the tree listing rather than a fetch per candidate: a source with no
    ``units.json`` is a source whose values are dimensionless, not a 404 worth reporting.
    A source with no ``vars.json`` at all *is* worth reporting — that is a mapping dir that
    has moved or was mistyped.
    """
    for key, mapping_dir in EXTRA_SOURCES:
        under = _under(tree, mapping_dir)
        staged = []
        for basename in EXTRA_SOURCE_FILES:
            blob = under.get(basename)
            if blob is None:
                continue
            target = TARGET_DIR / f"{key}_{basename}"
            target.write_bytes(fetch_blob(client, blob))
            staged.append(target.name)
        if staged:
            log.info("source %s: staged %s @ %s", key, ", ".join(staged), sha[:8])
        else:
            log.warning(
                "source %s: no %s under %s@%s; its definitions were not updated",
                key, " or ".join(EXTRA_SOURCE_FILES), mapping_dir, sha[:8],
            )


def trigger_reimport(client: httpx.Client) -> None:
    r = client.post(
        f"{API_URL}/internal/reimport",
        headers={"X-Internal-Token": INTERNAL_TOKEN},
    )
    r.raise_for_status()
    log.info("reimport: %s", r.json())


def _rows_digest(rows: list[dict], complete_for_types: list[str]) -> str:
    return hashlib.sha256(
        json.dumps([rows, sorted(complete_for_types)], sort_keys=True, default=str).encode()
    ).hexdigest()


def push_rows(client: httpx.Client, previous: str | None) -> str | None:
    """Post whatever this deployment *computes* (see sync/row_source.py); returns its digest.

    Separate from the reimport because it is a separate kind of thing: the files are fetched
    from upstream, these rows are derived here. The digest is kept across loop iterations the
    way the Notion export is, so an unchanged mapping file costs one hash instead of a POST of
    several thousand rows the API would find identical anyway.

    A generator that raised is not a reason to skip the cycle's reimport, so this contains its
    own failure — nothing is posted and the previous digest stands, which means the next
    cycle tries again rather than treating the missing rows as settled.
    """
    try:
        rows, complete_for_types = row_source.build_rows()
    except Exception as exc:  # noqa: BLE001 — the seam is deployment code; keep the loop alive
        log.warning("row generation failed (%s); posting no rows this cycle", exc)
        return previous
    if not rows:
        return previous

    digest = _rows_digest(rows, complete_for_types)
    if digest == previous:
        log.info("row upsert: %d row(s) unchanged since the last post; skipping", len(rows))
        return previous

    body: dict = {"rows": rows}
    if complete_for_types:
        # Only claim completeness for the types the generator actually finished. Anything it
        # dropped stays out, so a half-built type is never reported as having vanished.
        body["mode"] = "complete"
        body["complete_for_types"] = sorted(complete_for_types)
    r = client.post(
        f"{API_URL}/internal/variables/upsert",
        headers={"X-Internal-Token": INTERNAL_TOKEN},
        json=body,
    )
    r.raise_for_status()
    log.info("row upsert (%d row(s)): %s", len(rows), r.json())
    return digest


def sync_once(client: httpx.Client, sha: str, rows_digest: str | None = None) -> str | None:
    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    # One listing of the commit, shared by every pass below — including this first one, which
    # uses it to tell "this source doesn't have that file" from "the fetch failed".
    tree = list_tree(client, sha)
    for path in FILES:
        if path not in tree:
            log.warning("%s is not in %s@%s; skipping it", path, REPO, sha[:8])
            continue
        data = fetch_file(client, path, sha)
        (TARGET_DIR / Path(path).name).write_bytes(data)
        log.info("wrote %s (%d bytes) @ %s", Path(path).name, len(data), sha[:8])
    # After variables.py has landed: work out which data files it reads and stage those too.
    # A source that has no variables.py has no snippets, hence no data files to scan for and
    # no completion surface to build — the normal shape of a definitions-only source, so both
    # passes are skipped silently rather than reporting what was never there.
    if f"{MAPPING_DIR}/{VARIABLES_MODULE}" in tree:
        sync_variable_files(client, sha, tree)
        try:
            sync_pyapi(client, sha, tree)
        except Exception as exc:  # noqa: BLE001 — editor completions are not worth a failed sync
            log.warning(
                "pyapi generation failed (%s); keeping the previous %s", exc, pyapi.PYAPI_NAME
            )
    sync_extra_sources(client, sha, tree)
    # Only now reimport: the API attaches the staged files to the configs it creates, so
    # everything has to be in place before it runs.
    trigger_reimport(client)
    # …and after it, the variables this deployment computes from what was just staged.
    return push_rows(client, rows_digest)


# --- Notion documentation export -------------------------------------------------------------
# Duplicated in api/notion_pull.py, which gives `python -m api.reimport` the same export for
# deployments that run without this sidecar. The api and sync images are separate build
# contexts, so neither can import the other; a change here belongs there too.

def _notion_headers() -> dict[str, str]:
    return {
        "Authorization": f"Bearer {NOTION_API_KEY}",
        "Notion-Version": NOTION_VERSION,
    }


def _plain_text(rich: list | None) -> str | None:
    text = "".join((t.get("plain_text") or "") for t in (rich or [])).strip()
    return text or None


def _flatten_page(page: dict, fields: dict[str, str]) -> tuple[str, dict] | None:
    """One Notion page -> (title, doc dict in the shape api/importer.py applies)."""
    props = page.get("properties") or {}
    title = next(
        (_plain_text(p.get("title")) for p in props.values() if p.get("type") == "title"),
        None,
    )
    if not title:
        return None
    doc: dict[str, str | None] = {}
    for key in ("clinical", "implementation", "caveats"):
        prop = props.get(fields.get(key, ""), {})
        doc[key] = _plain_text(prop.get("rich_text")) if prop.get("type") == "rich_text" else None
    status_prop = props.get(fields.get("status", ""), {})
    doc["status"] = (status_prop.get("status") or {}).get("name") if status_prop.get("type") == "status" else None
    doc["url"] = page.get("url") or f"https://www.notion.so/{page['id'].replace('-', '')}"
    return title, doc


def fetch_notion_docs(client: httpx.Client) -> dict[str, dict]:
    """All pages of the documentation database, flattened per the field mapping.

    The 2025-09-03 API queries *data sources*, not databases, so the database's first data
    source is resolved on every refetch (it is stable, but this keeps the code stateless).
    """
    fields = json.loads(NOTION_FIELDS_FILE.read_text())
    r = client.get(f"{NOTION}/databases/{NOTION_DATABASE_ID}", headers=_notion_headers())
    r.raise_for_status()
    sources = r.json().get("data_sources") or []
    if not sources:
        raise RuntimeError("Notion database exposes no data source")
    ds_id = sources[0]["id"]

    docs: dict[str, dict] = {}
    cursor: str | None = None
    while True:
        body: dict = {"page_size": 100}
        if cursor:
            body["start_cursor"] = cursor
        r = client.post(
            f"{NOTION}/data_sources/{ds_id}/query", headers=_notion_headers(), json=body
        )
        r.raise_for_status()
        data = r.json()
        for page in data.get("results", []):
            flat = _flatten_page(page, fields)
            if flat:
                docs[flat[0]] = flat[1]
        if not data.get("has_more"):
            return docs
        cursor = data.get("next_cursor")


def notion_once(client: httpx.Client, previous: dict | None) -> dict | None:
    """One Notion refresh: write notion_docs.json and reimport only when the export changed.
    Returns the docs written (or `previous` unchanged); None means Notion is not configured."""
    if not (NOTION_API_KEY and NOTION_DATABASE_ID):
        return None
    docs = fetch_notion_docs(client)
    if docs == previous:
        return previous
    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    (TARGET_DIR / "notion_docs.json").write_text(json.dumps(docs, indent=1, sort_keys=True))
    log.info("wrote notion_docs.json (%d concepts documented)", len(docs))
    trigger_reimport(client)
    return docs


def main() -> None:
    notion_on = bool(NOTION_API_KEY and NOTION_DATABASE_ID)
    if not REPO and not notion_on:
        log.error("neither GITHUB_REPO nor NOTION_API_KEY+NOTION_DATABASE_ID set; refusing to start")
        sys.exit(1)
    if not INTERNAL_TOKEN:
        log.error("INTERNAL_TOKEN not set; refusing to start")
        sys.exit(1)

    if REPO:
        log.info("watching %s@%s every %ds -> %s", REPO, BRANCH, INTERVAL, API_URL)
    if notion_on:
        log.info("exporting Notion docs every %ds (mapping: %s)", NOTION_INTERVAL, NOTION_FIELDS_FILE)
    last: str | None = None
    rows_digest: str | None = None
    notion_docs: dict | None = None
    notion_due = 0.0  # first loop iteration fetches immediately
    with httpx.Client(timeout=30.0) as client:
        while True:
            if REPO:
                try:
                    sha = latest_sha(client)
                    if sha != last:
                        log.info("change detected: %s -> %s", (last or "none")[:8], sha[:8])
                        rows_digest = sync_once(client, sha, rows_digest)
                        last = sha  # only advance once the reimport succeeded
                except Exception as exc:  # noqa: BLE001 — keep the loop alive across transient errors
                    log.warning("sync cycle failed (%s); retrying in %ds", exc, INTERVAL)
            if notion_on and time.monotonic() >= notion_due:
                try:
                    notion_docs = notion_once(client, notion_docs)
                    notion_due = time.monotonic() + NOTION_INTERVAL
                except Exception as exc:  # noqa: BLE001
                    log.warning("notion export failed (%s); retrying in %ds", exc, INTERVAL)
            time.sleep(INTERVAL)


if __name__ == "__main__":
    main()
