from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    # MODE=PRODUCTION marks a deployment whose database is the system of record and must
    # never be rebuilt: destructive dev operations (the `?force=true` reimport, which wipes
    # the concept graph and with it every in-app edit) are refused with 403. Any other
    # value, including the default, leaves them available.
    mode: str = ""

    database_url: str = "sqlite:////data/concepts.db"
    jwt_secret: str = "change-me-in-production"
    jwt_algorithm: str = "HS256"
    token_expire_hours: int = 24

    # Bootstrap admin, created on first boot if there are no users yet.
    bootstrap_admin_username: str = "admin"
    bootstrap_admin_password: str = "admin"

    # Taxonomy a new concept's name is registered under by default.
    default_taxonomy: str = "corr_v1"

    # Folder of JSON-Schema files (per source/type), indexed by their $id. The folder is
    # the source of truth for validation and for which types a source supports.
    schema_dir: str = "reference/schema"
    # Reference data (sources, taxonomies, concepts) seeded on first run; rows are
    # inserted only if absent. The bootstrap admin is NOT here (it comes from env above).
    seed_file: str = "api/seed.yaml"

    # Import of the bundled reference datasets on boot (see api/importer.py): each variable in
    # a dataset's vars file becomes a concept + one published config for that dataset's source,
    # and a variable whose definition changed upstream gets a new version. Cheap to re-run —
    # unchanged variables are compared and skipped — so this stays on for a running deployment.
    import_reference_on_first_run: bool = True
    # The primary dataset, described by the `reference_*` settings below. It is the one that
    # can carry Python snippets, file attachments and the auto-generated medication/laboratory
    # variables, and the one the vars-sync sidecar refreshes in place.
    import_source_key: str = "cub_hdp"
    reference_vars_file: str = "reference/vars.json"
    reference_python_file: str = "reference/variables.py"
    # Optional {variable: unit} map folded into every definition of this dataset as a `unit`
    # field. Empty ⇒ the dataset states its units inside vars.json, if at all; the reprodicu
    # dataset below is what this exists for.
    reference_units_file: str = ""
    # Optional {variable: {taxonomy_key: [identifier, ...]}} map naming this dataset's
    # variables in taxonomies beside the key one. Merged with whatever `special_vars`
    # generates and maintained by the same import-owned pointer sync. Empty ⇒ the primary
    # dataset ships no pointer file (the public build's, which has none).
    reference_pointers_file: str = ""
    # Parquet mapping files a deployment's `special_vars` overlay generates its variables and
    # importer-managed pointers from (see api/special_vars.py). The vars-sync sidecar refreshes
    # these in the shared reference dir alongside vars.json; unused by the public no-op stub.
    reference_drug_parquet: str = "reference/drug_mapping.parquet"
    reference_lab_parquet: str = "reference/lab_mapping.parquet"
    # The primary source's data-file library, staged as a plain tree by the sidecar. The import
    # walks it and mints a new file version wherever the bytes differ from the current one (see
    # api/services.py). The tree is the whole truth: there is no manifest saying which variable
    # needs what, because a snippet says so itself with `getfile("<uuid>")`. An absent directory
    # means no files — the same no-op as a deployment without the sidecar.
    reference_files_dir: str = "reference/files"
    # The Python API surface (names + signatures + docstrings) the app's code editor completes
    # from, generated by the sidecar from upstream's helpers and the installed polars/pandas —
    # see sync/pyapi.py for the shape. Served as-is by GET /sources/{key}/pyapi; absent for a
    # deployment without the sidecar, which is a 404 there, not an error.
    reference_pyapi_file: str = "reference/pyapi.json"
    # Optional per-concept clinical documentation, exported from a Notion database by the
    # sync sidecar (see sync/sync.py): {name: {clinical, implementation, caveats, status,
    # url}}. Applied to the concept rows on every import/reimport; absent file = no-op.
    reference_notion_docs_file: str = "reference/notion_docs.json"
    # Further datasets imported alongside the primary one, each `{"source": <seeded source
    # key>, "vars": <vars.json>, "units": <units.json, optional>, "pointers": <pointers.json,
    # optional>}`. Definitions only: no Python snippets, no file attachments, no
    # auto-generated types — those belong to the primary source. Set REFERENCE_DATASETS to a
    # JSON array to change the list (`[]` imports the primary dataset alone).
    reference_datasets: list[dict[str, str]] = [
        {
            "source": "reprodicu",
            "vars": "reference/reprodicu_vars.json",
            "units": "reference/reprodicu_units.json",
            "pointers": "reference/reprodicu_pointers.json",
        },
    ]
    # Taxonomy the export's names (= Notion page titles) are resolved in. Empty ⇒ the
    # default taxonomy.
    notion_docs_taxonomy: str = ""
    # Credentials for pulling that export here rather than in the sidecar: `python -m
    # api.reimport` refreshes notion_docs.json before it upserts (see api/notion_pull.py).
    # Same names the sidecar reads, so one .env configures either mode. Key or database
    # unset ⇒ no pull, and the reimport says so. The fields file is the user-editable
    # column mapping; empty ⇒ notion_fields.json beside the docs file, else a built-in
    # default matching sync/notion_fields.json.
    notion_api_key: str = ""
    notion_database_id: str = ""
    notion_fields_file: str = ""
    # Message stamped on imported reference configs. TEMPORARY: during the read-only launch
    # this is overridden (env IMPORT_MESSAGE=Version currently not enabled) to signal that
    # the imported versions aren't queryable yet. Drop the override once the query API ships.
    import_message: str = "Imported from reference dataset"
    # Message stamped on the version the import mints when a variable's definition changed
    # upstream (`change_type='sync'`), which is what distinguishes an automated bump from an
    # authored one in the history.
    sync_import_message: str = "Automated sync from upstream reference"
    # Message stamped on the versions a *file* upload publishes (see the cascade in
    # api/services.py). Its own message rather than `sync_import_message`: the definition did
    # not move, a file it reads did, and a reader of the history has no other way to tell.
    file_sync_message: str = "Automated sync: a data file this definition reads was updated"

    # Types that are generated programmatically from mapping files (see api/special_vars.py)
    # rather than authored. Their configs are imported read-only and are never versioned or
    # editable through the browser; the write API refuses drafts of these types.
    auto_generated_types: list[str] = ["medication", "laboratory"]
    # Message stamped on the single (v1) config of every auto-generated variable, shown in
    # the UI in place of a real version/changelog.
    special_import_message: str = "Auto-generated variable, not versioned"
    # Types this deployment maintains through something other than the reference files —
    # typically the sidecar posting rows to POST /internal/variables/upsert (see
    # sync/row_source.py). They are excluded from the file-driven "no longer offered upstream"
    # report: a vars.json that never carried them is not evidence that they are gone. Without
    # this, moving generation out of `special_vars` makes every reimport report thousands of
    # perfectly live variables as missing, every poll interval, until nobody reads the report.
    externally_managed_types: list[str] = []

    # --- concept file attachments (see api/files.py) -----------------------------------
    # Where the content-addressed blob store keeps the bytes: <file_dir>/<sha[:2]>/<sha>.
    # A directory on the API's data volume, so attachments are backed up with the DB — the
    # DB only holds the digest, and a blob store without its rows (or vice versa) is useless.
    file_dir: str = "/data/files"
    # Per-upload ceiling. 64 MiB is well above the mapping tables that motivated this (the
    # largest upstream file is a few MB) while staying small enough that a single request
    # body is comfortably bufferable — these are lookup tables travelling with a definition,
    # not a dataset transfer channel.
    max_upload_bytes: int = 64 * 1024 * 1024
    # Suffixes an attachment may carry. An allowlist, not a denylist: these files are handed
    # to consumers who read them next to executable snippets, so anything that isn't a known
    # tabular/serialized data format has no business here.
    allowed_file_suffixes: list[str] = [
        ".csv", ".parquet", ".pkl", ".json", ".xlsx", ".txt", ".tsv",
    ]

    # Shared secret guarding POST /internal/reimport (called only by the vars-sync sidecar
    # over the compose network). Empty = endpoint disabled. Never exposed publicly.
    internal_token: str = ""

    # Shared secret the SvelteKit BFF sends as `X-App-Secret` to mark a request as coming
    # from our own web app. Concept read endpoints that carry it are treated as internal
    # browsing (no project required); every other client must name a valid `project`. Empty
    # ⇒ no request is trusted as app-originated. The BFF reads the same value from its env.
    app_shared_secret: str = ""

    # --- LDAP directory authentication ------------------------------------------------
    # Identity comes from LDAP; authorization stays in our DB. Disabled by default so
    # local/bootstrap login and the test suite work with no directory — deployments turn it
    # on and point it at their institution's server (ldap_auth is unit-tested with a mocked
    # connection).
    ldap_enabled: bool = False
    # LDAPS URI (SSL on 636), e.g. `ldaps://ldap.example.org:636`. StartTLS is not used —
    # we connect over SSL directly.
    ldap_server_uri: str = ""
    # Person DNs are often NOT a fixed template (they can live under varying OUs), so we
    # search for the uid first to resolve the DN, then re-bind as that DN to verify the
    # password. Scope the base to the canonical person roster: if the same uid appears on
    # multiple entries under the base (e.g. extra address/affiliation objects), the
    # uniqueness guard rejects the login.
    ldap_search_base: str = ""
    ldap_uid_filter: str = "(uid={username})"
    # Filter for the admin directory search (proactive provisioning): substring match on uid
    # or common name, so an admin can find a person who has never logged in and pre-grant
    # access. `{query}` is substituted with the escaped search term.
    ldap_search_filter: str = "(|(uid=*{query}*)(cn=*{query}*))"
    # Cap on how many directory-search hits we return (and request from the server).
    ldap_search_size_limit: int = 50
    # Immutable per-person directory attribute used as our stable join key (stored base64).
    # Pick your directory's non-reusable id: `entryUUID` (OpenLDAP), `objectGUID` (AD), or a
    # vendor-specific equivalent.
    ldap_guid_attribute: str = "entryUUID"
    ldap_display_name_attribute: str = "cn"
    # Bind used for the directory *search* step. Empty ⇒ anonymous bind; set a service
    # account DN/password if the directory restricts anonymous read.
    ldap_search_bind_dn: str = ""
    ldap_search_bind_password: str = ""
    # Path to a CA bundle to validate the LDAPS certificate. Empty ⇒ do NOT validate
    # (development only — set this in production; never ship unvalidated TLS).
    ldap_tls_ca_certs_file: str = ""
    # TEMPORARY: grant `can_read` to any user who authenticates against the directory and has
    # no capabilities yet, instead of leaving them pending an admin's approval. Everyone in
    # the directory can then read; every other capability still requires an explicit grant.
    # Turn off to return to approval-gated access (already-granted reads are NOT revoked).
    ldap_auto_grant_read: bool = False

    # --- Email notifications (Exchange Web Services) ----------------------------------
    # Outbound notifications are sent from a shared functional mailbox through Exchange Web
    # Services — the mailbox is an Exchange account (Outlook/OWA), not an SMTP submission
    # account, so mail goes out over EWS (see api/mailer.py). Recipients come from the LDAP
    # `mail` attribute. Disabled by default so local runs and the test suite never touch a
    # mail server; the deployment sets EXCHANGE_ENABLED=true and supplies the credentials.
    exchange_enabled: bool = False
    # Exchange host, e.g. `mail.example.org`. The EWS endpoint is derived from it:
    # https://<server>/EWS/Exchange.asmx. Autodiscover is not used, so this must be the
    # server that actually serves the mailbox.
    exchange_server: str = ""
    # Login, NOT necessarily the address: functional mailboxes are often served by a
    # separate account. If the server rejects the bare name, try the domain-qualified form
    # (`DOMAIN\user` or `user@example.org`) — `python -m api.mail_check` tries both.
    exchange_username: str = ""
    exchange_password: str = ""
    # The mailbox we send as, opened with the credentials above (delegate access).
    exchange_mailbox: str = ""
    # HTTP auth the server expects. NTLM is what on-prem Exchange normally speaks; "basic" and
    # "digest" are also accepted here, and an empty value lets exchangelib probe for it.
    exchange_auth_type: str = "NTLM"
    exchange_timeout: int = 20

    # Product name and contact address used in notification emails (see api/mailer.py).
    # An empty contact address omits the "reach out at ..." line.
    app_display_name: str = "Concepts Browser"
    contact_email: str = ""

    # Public origin of the web app, used to link users back to it from a notification email.
    frontend_origin: str = "http://localhost:3000"

    cors_origins: list[str] = ["*"]

    # Path prefix the API is served under by the reverse proxy (Caddy strips `/api` before
    # forwarding, so the app is unaware of it otherwise). Setting this makes the OpenAPI
    # docs and `servers` block emit correctly-prefixed URLs. Empty ⇒ served at domain root.
    root_path: str = ""


settings = Settings()
